#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

wclean src/jevGovernor
rm -f "$FOAM_USER_LIBBIN/libjevGovernor.so"

#------------------------------------------------------------------------------
